version: '3.9'

services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    environment:
      KESTRA_DATABASE_URL: jdbc:postgresql://postgres/kestra
      KESTRA_DATABASE_USERNAME: kestra
      KESTRA_DATABASE_PASSWORD: kestra
      MICRONAUT_SERVER_CORS_ENABLED: "true"
      MICRONAUT_SERVER_CORS_ALLOWEDORIGINS: "http://localhost:5173"
      MICRONAUT_SERVER_CORS_ALLOWEDMETHODS: "GET,POST,OPTIONS"
      MICRONAUT_SERVER_CORS_ALLOWEDHEADERS: "Content-Type,Authorization"
    ports:
      - "8080:8080"
    volumes:
      - ./kestra-flows:/data/flows  
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    container_name: kestra_postgres
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
      POSTGRES_DB: kestra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local


