id: special-letter
namespace: app.emails

tasks:
  - id: log-input
    type: io.kestra.plugin.core.log.Log
    message: >
      Received a letter:
      Text: {{ trigger.body.text }}
      Open At: {{ trigger.body.deliveryDate }}

  - id: save-to-database
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://kestra_postgres:5432/kestra
    username: kestra
    password: k3str4
    sql: |
      INSERT INTO letters (message, open_at) VALUES ('{{ trigger.body.text }}', '{{ trigger.body.deliveryDate }}');

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: abcdefg
